# Generated by Django 2.1.5 on 2019-02-16 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favcolor',
            field=models.TextField(default='Blue'),
            preserve_default=False,
        ),
    ]
