from base import conf

OVERDOSEDEATHS_PREFIX = "OVERDOSEDEATHS"

OVERDOSEDEATHS_VERBOSE_NAME = "OverdoseDeaths"
OVERDOSEDEATHS_VERBOSE_NAME_PLURAL = "OverdoseDeaths"

OVERDOSEDEATHS_LIST_URL_NAME = OVERDOSEDEATHS_PREFIX + conf.LIST_SUFFIX
OVERDOSEDEATHS_CREATE_URL_NAME = OVERDOSEDEATHS_PREFIX + conf.CREATE_SUFFIX
OVERDOSEDEATHS_DETAIL_URL_NAME = OVERDOSEDEATHS_PREFIX + conf.DETAIL_SUFFIX
OVERDOSEDEATHS_UPDATE_URL_NAME = OVERDOSEDEATHS_PREFIX + conf.UPDATE_SUFFIX
OVERDOSEDEATHS_DELETE_URL_NAME = OVERDOSEDEATHS_PREFIX + conf.DELETE_SUFFIX

PRESCRIPTION_PREFIX = "PRESCRIPTION"

PRESCRIPTION_VERBOSE_NAME = "Prescription"
PRESCRIPTION_VERBOSE_NAME_PLURAL = "Prescription"

PRESCRIPTION_LIST_URL_NAME = PRESCRIPTION_PREFIX + conf.LIST_SUFFIX
PRESCRIPTION_CREATE_URL_NAME = PRESCRIPTION_PREFIX + conf.CREATE_SUFFIX
PRESCRIPTION_DETAIL_URL_NAME = PRESCRIPTION_PREFIX + conf.DETAIL_SUFFIX
PRESCRIPTION_UPDATE_URL_NAME = PRESCRIPTION_PREFIX + conf.UPDATE_SUFFIX
PRESCRIPTION_DELETE_URL_NAME = PRESCRIPTION_PREFIX + conf.DELETE_SUFFIX

DRUG_PREFIX = "DRUG"

DRUG_VERBOSE_NAME = "Drug"
DRUG_VERBOSE_NAME_PLURAL = "Drug"

DRUG_LIST_URL_NAME = DRUG_PREFIX + conf.LIST_SUFFIX
DRUG_CREATE_URL_NAME = DRUG_PREFIX + conf.CREATE_SUFFIX
DRUG_DETAIL_URL_NAME = DRUG_PREFIX + conf.DETAIL_SUFFIX
DRUG_UPDATE_URL_NAME = DRUG_PREFIX + conf.UPDATE_SUFFIX
DRUG_DELETE_URL_NAME = DRUG_PREFIX + conf.DELETE_SUFFIX

DOCTOR_PREFIX = "DOCTOR"

DOCTOR_VERBOSE_NAME = "Doctor"
DOCTOR_VERBOSE_NAME_PLURAL = "Doctor"

DOCTOR_LIST_URL_NAME = DOCTOR_PREFIX + conf.LIST_SUFFIX
DOCTOR_CREATE_URL_NAME = DOCTOR_PREFIX + conf.CREATE_SUFFIX
DOCTOR_DETAIL_URL_NAME = DOCTOR_PREFIX + conf.DETAIL_SUFFIX
DOCTOR_UPDATE_URL_NAME = DOCTOR_PREFIX + conf.UPDATE_SUFFIX
DOCTOR_DELETE_URL_NAME = DOCTOR_PREFIX + conf.DELETE_SUFFIX

