# Generated by Django 2.1.5 on 2019-04-08 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.TextField(default='Doctor First Name')),
                ('lastName', models.TextField(default='Doctor Last Name')),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='F', max_length=1)),
                ('credentials', models.TextField(default='Doctor Credentials')),
                ('location', models.TextField(default='Doctor Location')),
                ('specialty', models.TextField(default='Doctor Specialty')),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Drug Name')),
                ('drugType', models.CharField(choices=[('T', 'Is Opiate'), ('F', 'Is Not Opiate')], default='T', max_length=1)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('prescriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Doctor')),
            ],
        ),
    ]
