# Generated by Django 2.1.5 on 2019-04-09 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=20)),
            ],
        ),
        migrations.RenameField(
            model_name='drug',
            old_name='name',
            new_name='drugName',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='prescriber',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='quantity',
        ),
        migrations.AddField(
            model_name='doctor',
            name='doctorID',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='opioidPrescriber',
            field=models.CharField(choices=[('F', 'False'), ('T', 'True')], default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='doctor',
            name='totalPrescriptions',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drug',
            name='drugType',
            field=models.CharField(choices=[('F', 'Is Not Opiate'), ('T', 'Is Opiate')], default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Doctor'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='drugName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Drug'),
        ),
    ]
