# Generated by Django 2.1.5 on 2019-04-09 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20190409_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverdoseDeaths',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.TextField(default='State')),
                ('population', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='firstName',
            new_name='fName',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='lastName',
            new_name='lName',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='location',
            new_name='state',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='credentials',
            field=models.TextField(default='none'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctorID',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='opioidPrescriber',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='overdosedeaths',
            name='abbrev',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Doctor'),
        ),
    ]
