# Generated by Django 2.1.5 on 2019-04-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20190409_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='id',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctorID',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
