# Generated by Django 2.1.5 on 2019-04-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20190409_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='credentials',
            field=models.TextField(default='none', null=True),
        ),
    ]
