# Generated by Django 2.1.5 on 2019-04-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20190409_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctorID',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
